name: haruna
confinement: strict
grade: stable
base: core22
adopt-info: haruna
#icon: $CRAFT_PROJECT_DIR/data/icons/128-apps-haruna.png

apps:
  haruna:
    extensions:
      - kde-neon-6
    common-id: org.kde.haruna
    desktop: usr/share/applications/org.kde.haruna.desktop
    command: usr/bin/haruna
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH 
      LC_NUMERIC: C
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - desktop
      - opengl
      - wayland
      - x11
      - home
      - network
      - network-bind
      - audio-playback
      - removable-media
      - unity7
      - screen-inhibit-control
      - mount-observe
      - udisks2
compression: lzo

plugs:
  ffmpeg-2204:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2204


slots:
  haruna:
    interface: dbus
    name: org.kde.haruna
    bus: session
  mpris:
    interface: mpris
    name: haruna

parts:
  ninja:
    plugin: nil
    source: https://github.com/ninja-build/ninja.git
    source-tag: 'v1.11.1'
    source-depth: 1
    override-build: |
      rm -rf build
      rm -f ninja
      rm -f ninja_bootstrap
      sed -i 's_^#!/usr/bin/env python$_#!/usr/bin/env python3_g' configure.py
      ./configure.py --bootstrap
      mv ninja ninja_bootstrap
      rm -rf build
      ./ninja_bootstrap
      rm -f ninja_bootstrap
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mv ninja $CRAFT_PART_INSTALL/usr/bin/
    build-packages:
      - python3

  meson-deps:
    after: [ ninja ]
    plugin: nil
    source: https://github.com/mesonbuild/meson.git
    source-tag: '1.2.3'
    source-depth: 1
    override-build: |
      python3 -m pip install .
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/meson*
      python3 -m pip install --target=$CRAFT_PART_INSTALL/usr .
      mv $CRAFT_PART_INSTALL/usr/meson* $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" /usr/local/bin/meson
    build-packages:
      - python3-pip

  shaderc:
    source: https://github.com/google/shaderc.git
    source-tag: 'v2024.3'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DSHADERC_SKIP_TESTS=ON
      - -DSHADERC_SKIP_EXAMPLES=ON
      - -DSHADERC_SKIP_COPYRIGHT_CHECK=ON
      - -DSPIRV_SKIP_EXECUTABLES=ON
    build-environment:
      - PKG_CONFIG_PATH: /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:/usr/lib/pkgconfig
    build-snaps:
      - cmake
    override-pull: |
      craftctl default
      python3 $CRAFT_PART_SRC/utils/git-sync-deps
    prime:
      - -usr/bin
      - -usr/include
      - -usr/*/*/pkgconfig
      - -usr/*/*/cmake
      - -usr/lib/*/libSPIRV*
      - -usr/lib/*/*.a

  libplacebo:
    after: [meson-deps, shaderc]
    source: https://code.videolan.org/videolan/libplacebo.git
    source-tag: 'v7.349.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dtests=false
      - -Dvulkan=enabled
      - -Dglslang=enabled 
      - -Dshaderc=enabled 
      - -Dlcms=enabled
      - -Dd3d11=disabled
      - -Ddemos=false
    build-snaps:
      - ffmpeg-2204-sdk
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    prime:
      - usr/lib/*/libplacebo*
    build-packages:
      - libvulkan-dev
      - python3-jinja2
      - glslang-dev
      - libopengl-dev
      - liblcms2-dev

  mpv:
    after: [meson-deps, libplacebo]
    source: https://github.com/mpv-player/mpv.git
    source-tag: 'v0.38.0'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - -Dlibmpv=true
      - -Ddrm=enabled
      - -Dwayland=enabled
      - -Dx11=enabled
    build-snaps:
      - ffmpeg-2204-sdk
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    build-packages:
      - libass-dev
      - libdrm-dev
      - libjpeg-turbo8-dev
      - libv4l-dev
      - libpulse0
      - libwayland-dev
      - wayland-protocols
      - libxpresent-dev
      - libxss-dev
      - libxkbcommon-dev
    prime:
      - usr/bin/mpv
      - usr/lib/*/libmpv*
    organize:
      snap/haruna/current: .

  mpvqt:
    after: [mpv]
    source: https://invent.kde.org/libraries/mpvqt.git
    source-depth: 1
    source-tag: 'v1.0.1'
    plugin: cmake
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DLibmpv_LIBRARIES=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmpv.so
      - -DLibmpv_INCLUDE_DIRS=$CRAFT_STAGE/usr/include

  python-deps:
    source: .
    plugin: python
    python-packages:
      - yt-dlp
    prime:
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.10
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -usr/bin/wheel
      - -usr/lib/python3.10/dist-packages/pip*
      - -usr/lib/python3.10/dist-packages/pkg_resources
      - -usr/lib/python3.10/dist-packages/setuptools*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
      - -share
    organize:
      bin: usr/bin
      lib/python3.10/site-packages: usr/lib/python3/dist-packages

  haruna:
    after: [mpvqt, python-deps]
    parse-info:
      - usr/share/metainfo/org.kde.haruna.metainfo.xml
    plugin: cmake
    build-packages:
      - docbook
      - docbook-xml
      - docbook-xsl
      - libass-dev
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - libpulse0
      - libv4l-0
      - libxkbcommon-dev
      - libvulkan-dev
      - pkg-config
      - gettext
    build-snaps:
      - ffmpeg-2204-sdk
      - cmake
    source: https://invent.kde.org/multimedia/haruna/-/archive/v1.2.1/haruna-v1.2.1.tar.gz 
    build-environment:
      - PKG_CONFIG_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Debug
      - -DKDE_SKIP_TEST_SETTINGS=ON
      - -DLibmpv_LIBRARIES=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmpv.so
      - -DLibmpv_INCLUDE_DIRS=$CRAFT_STAGE/usr/include
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/doc/*
      - -usr/share/man/*
      - -usr/share/icons/breeze-dark*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell

  cleanup:
    plugin: nil
    after: [haruna]
    stage-packages:
      - libxpresent1
      - pulseaudio
      - libpulse0
